=== BBence-dev/ILVJQO_GYAK/XMLTaskIVLJQO/XMLSchemaIVLJQO.xsd
<!—verzió szam karakterkódolás-->
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema targetNamespace="ivljqo" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!—öszetett tipus elem ami a lakcimTipus névre halgat-->
<xs:complexType name="lakcimTipus">
<!—a gyerekelemeket a szekvencia tagek között kell megadni -->
<!—nyitótag-->
    <xs:sequence>
<!—gyerek elemek-->
      <xs:element type="xs:string" name="varos"/>
      <xs:element type="xs:string" name="iranyitoszam"/>
      <xs:element type="xs:string" name="utca"/>
      <xs:element type="xs:string" name="hazszam"/>
<!—zárotag-->
    </xs:sequence>
<!—zárotag-->
  </xs:complexType>
  <!—öszetett tipus elem ami a lakcimTipus névre halgat nyitó tag-->
  <xs:complexType name="lakcimekTipus">
    <xs:sequence>
<!—meghatározzuk hányszor fordulhat elö egy elem-->
      <xs:element type="lakcimTipus" name="lakcim" maxOccurs="unbounded" minOccurs="0"/>
<!—zárotagek-->
    </xs:sequence>
  </xs:complexType>
<!—komlex tipus ami több fajta tipus is felvehet egyben nyitó tag-->
  <xs:complexType name="vevo" mixed="true">
    <xs:sequence>
      <xs:element name="nev" />
      <xs:element name="telefonszam" />
<!—hivatkozási elem a saját tipusunkra-->
      <xs:element type="fizetesTipus" name="fizetes" />
      <xs:element type="lakcimekTipus" name="lakcim" />
      <xs:element type="rendelesadatokTipus" name="rendeles" />
    </xs:sequence>
<!—idegen kulcsokra való hivatkozás-->
    <xs:attribute type="xs:string" name="idref" />
    <xs:attribute type="xs:string" name="id" />
  </xs:complexType>
  <!—öszetett tipus elem ami a vevokTipus névre halgat-->
  <xs:complexType name="vevokTipus">
    <xs:sequence>
<!—meghatározzuk hogy hányszor fordulhat elő egy vevő tipus
      <xs:element type="vevotipus" name="vevo" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>
  <!—öszetett tipus elem ami a rendelesadatokTipus névre halgat-->
  <xs:complexType name="rendelesadatokTipus">
    <xs:sequence>
      <xs:element type="erkezesTipus" name="erkezes"/>
      <xs:element type="xs:string" name="datum"/>
      <xs:element type="etteremekTipus" name="etterem"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="idref" />
  </xs:complexType>
<!—öszetett tipus elem ami a rendelesadatokTipus névre halgat-->
  <xs:complexType name="rendelesadatokTipus">
    <xs:sequence>
      <xs:element type="rendelesTipus" name="rendeles"/>
    </xs:sequence>
  </xs:complexType>
<!—öszetett tipus elem ami a etteremTipus névre halgat-->
<!—több fajta tipust is felvehet-->
  <xs:complexType name="etteremTipus" mixed="true">
    <xs:sequence>
<!—elemek és elem hivtkozások-->
      <xs:element type="xs:string" name="nev"/>
      <xs:element type="fizetesTipus" name="fizetes"/>
      <xs:element type="xs:string" name="telefonszam"/>
      <xs:element type="lakcimekTipus" name="lakcim"/>
      <xs:element type="rendelesadatokTipus" name="rendeles"/>
      <xs:element type="xs:string" name="weblap"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="idref" />
    <xs:attribute type="xs:string" name="id" />
  </xs:complexType>
<!—öszetett tipus elem ami a etteremTipus névre halgat-->
  <xs:complexType name="ettermekTipus">
    <xs:sequence>
<!—meghatározzuk hogy hányszor fordulhat elő egy etterm tipus-->
      <xs:element type="etteremTipus" name="etterem" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
<!—öszetett tipus elem ami a etlapTipus névre halgat-->
  <xs:complexType name="etlapTipus">
    <xs:sequence>
<!—elemek meg adása hivatkozás egy másik elemra-->
      <xs:element name="nev" />
      <xs:element name="darab" />
      <xs:element name="osszeg" />
      <xs:element type="rendelesadtakTipus" name="date" />
    </xs:sequence>
<!—kulcsokra való hivatkozása-->
    <xs:attribute type="xs:string" name="idref" />
    <xs:attribute type="xs:string" name="id" />
  </xs:complexType>
<!—öszetett tipus elem ami a etlapokTipus névre halgat-->
  <xs:complexType name="etlapokType">
    <xs:sequence>
      <xs:element type="etlapTipus" name="etlap" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="erkezesTipus">
    <xs:sequence>
      <xs:element name="tol" />
      <xs:element name="ig" />
    </xs:sequence>
  </xs:complexType>

<xs:complexType name="fizetesTipus">
    <xs:sequence>
      <xs:element name="keszpenz" />
      <xs:element name="kartya" />
    </xs:sequence>
  </xs:complexType>
<!—adatok gyökér elem elemi egyedi tipusok
  <xs:element name="adatok">
<!—komplex tipus benne a saját tipusok-->
    <xs:complexType>
      <xs:sequence>
        <xs:element type="lakcimekTipus" name="lakcimek"/>
        <xs:element type="vevokTipus" name="vevok"/>
        <xs:element type="rendelesadatokTipus" name="rendeles"/>
        <xs:element type="ettermekTipus" name="ettermek"/>
        <xs:element type="etlapokTipus" name="etlapok"/>
      </xs:sequence>
    </xs:complexType>
<!—a kulcs neve-->
    <xs:key name="lakcimId">
      <!—az elérési útvonal hogy honnan legyen az elsődleges kulcs-->
       <xs:selector xpath="./lakcimek/lakcim"/>
         <!—amiben tárolódik a kulcs attribútuma-->
      <xs:field xpath="@id" />
        <!—zárotag-->
    </xs:key>
	<!—a kulcs neve-->
    <xs:key name="vevoId">
	<!—az elérési útvonal hogy honnan legyen az elsődleges kulcs-->
      <xs:selector xpath="./vevok/vevo"/>
	<!—amiben tagolódik a kulcs attribútuma-->
      <xs:field xpath="@id" />
	<!—zárotag-->
    </xs:key>
	<!—a kulcs neve-->
    <xs:key name="rendelesID">
	<!—az elérési útvonal hogy honnan legyen az elsődleges kulcs-->
      <xs:selector xpath="./rendelesadatok/rendeles"/>
	<!—amiben tagolódik a kulcs attribútuma-->
      <xs:field xpath="@id" />
	<!—zárotag-->
    </xs:key>
	<!—a kulcs neve-->
    <xs:key name="etteremID">
	<!—az elérési útvonal hogy honnan legyen az elsődleges kulcs-->
      <xs:selector xpath="./ettermek/etterem"/>
	<!—amiben tagolódik a kulcs attribútuma-->
      <xs:field xpath="@id" />
<!—zárotag-->
    </xs:key>
	<!—a kulcs neve-->
    <xs:key name="etlapID">
	<!—az elérési útvonal hogy honnan legyen az elsődleges kulcs-->
      <xs:selector xpath="./etlapok/etlap"/>
	<!—amiben tagolódik a kulcs attribútuma-->
      <xs:field xpath="@id" />
	<!—zárotag-->
    </xs:key>

    <xs:keyref name="rendelesRef" refer="rendelesId">
      <xs:selector xpath="./ettermek/etterem/rendelesadatok/rendeles"/>
      <xs:field xpath="@idref" />
    </xs:keyref>
    <xs:keyref name="lakcimRef" refer="lakcimId">
      <xs:selector xpath="./vevok/vevo/lakcimek/lakcim"/>
      <xs:field xpath="@idref" />
    </xs:keyref>
    <xs:keyref name="ettermekRef" refer="etteremID">
      <xs:selector xpath="./rendelesadatok/rendeles/ettermek/etterem"/>
      <xs:field xpath="@idref" />
    </xs:keyref>
  </xs:element>
</xs:schema><!—schema zárotagje-->

=== BBence-dev/ILVJQO_GYAK/XMLTaskIVLJQO/Updated_XMLIVLJQO.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<adatok xmlns="ivljqo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="ivljqo XMLSchemaIVLJQO.xsd">
    
    <ettermek>
        	
        <etterem id="1">
                		
            <nev>Egyszer étterem</nev>
                		
            <telefonszam>06704564653</telefonszam>
                		
            <weblap>www.egyszeretterem.com</weblap>
            	
            <rendelesadatok>
                		
                <rendeles idref="1"/>
                	
            </rendelesadatok>
             
	
            <kapacitas>500</kapacitas>
        </etterem>
        		 
	
        <etterem id="2">
                		
            <nev>Jó étterem</nev>
                		
            <telefonszam>06704569873</telefonszam>
               		
            <weblap>www.joetterem.com</weblap>
            	
            <rendelesadatok>
                		
                <rendeles idref="2"/>
                	
            </rendelesadatok>
             	
            <kapacitas>500</kapacitas>
        </etterem>
        	
        <etterem id="3">
                		
            <nev>Volt étterem</nev>
                		
            <telefonszam>06704659873</telefonszam>
                		
            <weblap>www.voltetterem.com</weblap>
            	
            <rendelesadatok>
                		
                <rendeles idref="3"/>
                	
            </rendelesadatok>
              	
            <kapacitas>500</kapacitas>
        </etterem>
        	
 
    </ettermek>
    
    <vevok>
         		
        <vevo id="1">
                			
            <nev>Ádám</nev>
                		
            <fizetes>
                      			
                <keszpenz>10000</keszpenz>
                      			
    		
            </fizetes>
                		
            <telefonszam>06703333456</telefonszam>
                		
            <lakcimek>
                			
                <lakcim idref="1"/>
                		
            </lakcimek>
            		
            <rendelesadatok>
                			
                <rendeles idref="1"/>
                		
            </rendelesadatok>
             
  		
            <kor>22</kor>
        </vevo>
          		
        <vevo id="2">
                			
            <nev>Zsófi</nev>
                		
            <fizetes>
                      			
                <keszpenz>500</keszpenz>
                      			
    		
            </fizetes>
                			
            <telefonszam>06706343353</telefonszam>
                		
            <lakcimek>
                			
                <lakcim idref="2"/>
                		
            </lakcimek>
            		
            <rendelesadatok>
                			
                <rendeles idref="2"/>
                		
            </rendelesadatok>
              		
            <kor>22</kor>
        </vevo>
          		
        <vevo id="3">
                			
            <nev>Sándor</nev>
                		
            <fizetes>
                      			
                <keszpenz>1500</keszpenz>
                      			
    		
            </fizetes>
                			
            <telefonszam>06706343353</telefonszam>
                		
            <lakcimek>
                			
                <lakcim idref="3"/>
                		
            </lakcimek>
            		
            <rendelesadatok>
                			
                <rendeles idref="3"/>
                		
            </rendelesadatok>
              		
            <kor>22</kor>
        </vevo>
        
    </vevok>
    
    <lakcimek>
        	
        <lakcim id="1">
                  		
            <varos>Sátor</varos>
                  		
            <iranyitoszam>3970</iranyitoszam>
                  		
            <utca>Paloc</utca>
                  		
            <hazszam>2</hazszam>
                	
        </lakcim>
        	
        <lakcim id="2">
                  		
            <varos>Sátor</varos>
                  		
            <iranyitoszam>3970</iranyitoszam>
                  		
            <utca>Lolka</utca>
                  		
            <hazszam>4</hazszam>
                	
        </lakcim>
        	
        <lakcim id="3">
                  		
            <varos>Sátor</varos>
                  		
            <iranyitoszam>3970</iranyitoszam>
                  		
            <utca>Lolka</utca>
                  		
            <hazszam>4</hazszam>
                	
        </lakcim>
         
    </lakcimek>
    	

 
    <rendelesadatok>
         

	
        <rendeles id="1">
                		
            <erkezes>
                      			
                <tol>2022.06.08.18:40</tol>
                      			
                <ig>2022.06.08.19:30</ig>
                    		
            </erkezes>
            	
            <datum>2022.06.08.18:00</datum>
            	
            <ettermek>
                		
                <etterem idref="1">
                    <kapacitas>500</kapacitas>
                </etterem>
                	
            </ettermek>
            	
        </rendeles>
        	
  	
        <rendeles id="2">
                		
            <erkezes>
                      			
                <tol>2022.07.09.18:40</tol>
                      			
                <ig>2022.07.09.19:30</ig>
                    		
            </erkezes>
            	
            <datum>2022.07.09.18:00</datum>
            	
            <ettermek>
                		
                <etterem idref="2">
                    <kapacitas>500</kapacitas>
                </etterem>
                	
            </ettermek>
              	
        </rendeles>
          	
        <rendeles id="3">
                		
            <erkezes>
                      			
                <tol>2022.06.09.18:40</tol>
                      			
                <ig>2022.06.09.19:30</ig>
                    		
            </erkezes>
            	
            <datum>2022.06.09.18:00</datum>
            	
            <ettermek>
                		
                <etterem idref="3">
                    <kapacitas>500</kapacitas>
                </etterem>
                	
            </ettermek>
              	
        </rendeles>
         
    </rendelesadatok>
    
    <etlapok>
          		
        <etlap id="1">
                			
            <nev>Pizza</nev>
                			
            <darab>5</darab>
                			
            <osszeg>10000</osszeg>
            		
            <rendelesadatok>
                			
                <rendeles idref="1"/>
                		
            </rendelesadatok>
             
  		
        </etlap>
         		
        <etlap id="2">
                			
            <nev>Hamburger</nev>
                			
            <darab>1</darab>
                			
            <osszeg>500</osszeg>
            		
            <rendelesadatok>
                			
                <rendeles idref="2"/>
                		
            </rendelesadatok>
             
  		
        </etlap>
          		
        <etlap id="3">
                			
            <nev>Gyros</nev>
                			
            <darab>1</darab>
                			
            <osszeg>1500</osszeg>
            		
            <rendelesadatok>
                			
                <rendeles idref="3"/>
                		
            </rendelesadatok>
             
  		
        </etlap>
        
    </etlapok>
    
</adatok>
